### ISSUE TITLE
Make .strangelogrc optional

### ISSUE THREAD

**Issue by Kadrian** [neXenio/strangelog#4]
*Assumptions*

1) In many cases, I have a repository that only concerns a single project or component. Then, changelog entries shouldn't necessarily be prefixed with anything.

2) Convention over configuration: `changelog` is a sane default path for changelog entries.

*Proposal*
When I'm not providing a `.strangelogrc`, I expect strangelog's `add`, `bump`, `generate` commands to work (in the most simple fashion).

*Current behavior*
```
> strangelog add
Error: No .strangelogrc found in working directory
```

**Comment by leoselig** [comment]
Technically, this would require 2 changes:
1. No `.strangelogrc` would default to something like this:
```javascript
path: './changelog'
components: []
```
2. We must support "no" configured components to result in
- no prompt for a component during `$ add`
- no components in generated markdown
